### ISSUE TITLE
我怀疑加了MVVM之后，热更新没有效果了

### ISSUE THREAD

**Issue by kamike** [unicreators/mvvm#10]
项目中加了mvvm之后，在Android studio每次保存之后，hot reload都会自动跳转到第一个界面，只是修改字体大小，保存之后都是这样。新建的项目没有用mvvm就不会，我怀疑是这个框架的bug，没有报错信息，暂时还没有找到证据。

**Comment by unicreators** [comment]
@kamike MVVM示例代码在模拟器中没出现这种情况，可否贴出你的代码？

**Comment by kamike** [comment]
抱歉，写了个demo，发现没有问题，最后查出来是我项目的代码有问题
