### ISSUE TITLE
返回到界面没有回调方法

### ISSUE THREAD

**Issue by kamike** [unicreators/mvvm#11]
当跳转到一个新的界面，返回到当前页面可能要刷新数据，类似deactivate()，但是在view里面没有类似方法，虽然可以通过路由then()之后回调，但是还是不方便，不知道可不可以加上

**Comment by unicreators** [comment]
@kamike  可以试试在ViewModel 里加入自定义刷新数据方法(见下 reload 方法)，并在View中公开它，deactivate时调用即可，不知道是不是能解决你的问题。

`
class Demo1ViewModel extends ViewModel {
  Demo1ViewModel() {
    propertyValue<String>(#time, initial: "");
    start();
  }

  start() {
    Timer.periodic(const Duration(seconds: 1), (_) {
      var now = DateTime.now();
      setValue<String>(#time, "${now.hour}:${now.minute}:${now.second}");
    });
  }

 reload() {
      // ...
  }
  
}`

`
class Demo1View extends View<Demo1ViewModel> {
  Demo1View() : super(Demo1ViewModel());

  @override
  Widget build(BuildContext context) {
    return ...;
  }

  reload() {
      $Model.reload();
  }

}`

**Comment by kamike** [comment]
非常感谢作者回答，最关键的问题是deactivate这个方法在View里面没有override

**Comment by kamike** [comment]
![image](https://user-images.githubusercontent.com/3920019/86690211-4ebf0880-c03a-11ea-88dc-aa99b351bf80.png)
View的父类里面没有deactivate方法

**Comment by kamike** [comment]
我搞错了，实际上是可以通过RouteAware来监听页面的
