### ISSUE TITLE
View里面有TabController就用不了

### ISSUE THREAD

**Issue by kamike** [unicreators/mvvm#13]
class MyView extends View<MyViewModel> {
MyView (): super(MyViewModel()){
TabController tableController = TabController(vsync: this, length: tableTypes.length);
}
}

TabController初始化当前类必须with TickerProviderStateMixin
View是不可以with  TickerProviderStateMixin

所以就用不了带TabController的控件了

**Comment by pishguy** [comment]
@kamike 

how could you resolve this problem?
