### ISSUE TITLE
1.12.13示例代码报错

### ISSUE THREAD

**Issue by Aaminly** [unicreators/mvvm#7]
1.12.13示例代码报错

Launching lib/main.dart on iPhone 11 in debug mode...

Compiler message:
../../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/mvvm-0.1.7/lib/view_context_helpers/logical.dart:151:25: Error: The function expression type 'Widget Function(BuildContext, Null, Widget) Function(TValue)' isn't of expected type 'Widget Function(BuildContext, TValue, Widget) Function(TValue)'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../../../Documents/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../Documents/flutter/packages/flutter/lib/src/widgets/framework.dart').
Change the type of the function expression or the context in which it is used.
              selector: (TValue value) =>
                        ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11.

**Comment by unicreators** [comment]
@Aaminly 已修复，感谢反馈。

**Comment by kamike** [comment]
我也是同样的编译错误，运行不起来。是不是要发布新版本才能正常运行？？
